services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: desk_management
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - ./storage/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3307:3306"
  fastapi:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: desk_management
      DB_USER: appuser
      DB_PASSWORD: apppass
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
